### ISSUE TITLE
No peaks on non-standard species

### ISSUE THREAD

**Issue by MBrancoLab** [maxsonBraunLab/gopeaks#10]
Hi,

We've been running goPeaks on some mouse data and it's been working really well (thanks for developing this!). But we've now applied it to a different rodent species and it's coming out with no peaks, even though the data look fine. There are also no errors and no extra info with verbose. So I'm a bit clueless. My only suspicion is that it might have something to do with the weird chromosome names used in this assembly, e.g.:

`@HD	VN:1.5	SO:unsorted	GO:query
@SQ	SN:ENA|LT608296|LT608296.1	LN:172151128
@SQ	SN:ENA|LT608289|LT608289.1	LN:116904986
@SQ	SN:ENA|LT608304|LT608304.1	LN:77350604
@SQ	SN:ENA|LT608305|LT608305.1	LN:89017189
@SQ	SN:ENA|LT608299|LT608299.1	LN:96704406
@SQ	SN:ENA|LT608308|LT608308.1	LN:88915856
`

Any chance you could have a look? I can send a bam file.

Thanks

Miguel

**Comment by gartician** [comment]
Hi @MBrancoLab,

Thank you for the kind words! I think you may be right in that the chromosome names may explain why GoPeaks doesn't call peaks. Can you filter for one (or a couple) scaffold but keep all the reads, and send that BAM file to me as the test dataset? Please share the file to my preferred email [kongga2017@gmail.com](mailto:kongga2017@gmail.com) using whatever sharing platform you like.

**Comment by MBrancoLab** [comment]
Now that's a quick reply! Will email now.
Thanks

**Comment by MBrancoLab** [comment]
Issue solved in GoPeaks 1.1.0 and 1.1.1, with thanks.
