### ISSUE TITLE
If no control, how to use this GoPeaks for peak calling

### ISSUE THREAD

**Issue by haixiashang** [maxsonBraunLab/gopeaks#6]

**Comment by gartician** [comment]
Hello @haixiashang,

Thank you for your interest in using GoPeaks. To use it without any controls, just omit the -c argument. So something like this: 

```bash
gopeaks -b <sample>.bam -o path/to/gopeaks/<sample>
```

**Comment by haixiashang** [comment]
Got it，thanks &nbsp;a lot!



发自我的iPhone


------------------ Original ------------------
From: Garth Kong ***@***.***&gt;
Date: Fri,Apr 21,2023 5:42 AM
To: maxsonBraunLab/gopeaks ***@***.***&gt;
Cc: haixiashang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [maxsonBraunLab/gopeaks] If no control, how to use this GoPeaksfor peak calling (Issue #6)





 
Hello @haixiashang,
 
Thank you for your interest in using GoPeaks. To use it without any controls, just omit the -c argument. So something like this:
 gopeaks -b <sample&gt;.bam -o path/to/gopeaks/<sample&gt;
