### ISSUE TITLE
Number of cores ?

### ISSUE THREAD

**Issue by divyanshusrivastava** [maxsonBraunLab/gopeaks#8]
Hi, 

How can I control the number of cores/thread used ?

Thanks

**Comment by gartician** [comment]
Hi @divyanshusrivastava,

Sorry for the delay in our response. We are currently looking into ways to constrain core usage in GoPeaks. We will definitely notify you when the change is implemented!

**Comment by gartician** [comment]
Hi @divyanshusrivastava,

Consider using [Summit](https://github.com/gartician/summit), an ultralight and fast version of GoPeaks that uses 1/5 the memory and 1/3 the time to process your samples. While Summit is limited to using one core, I think its efficiency can benefit every user.  Please let me know if this is helpful for your analysis!
