### ISSUE TITLE
Calling peaks is Killed when reading in chromsome sizes

### ISSUE THREAD

**Issue by Affebah** [maxsonBraunLab/gopeaks#9]
Hi,

Im trying to use GoPeaks peak calling on ACT-seq samples, however the process is "Killed" due to  some reason. Running in verbose mode to see what happens the process doesnt seem get past the reading in chromesize step. How would you input chromsome sizes in the command line, in my case for mm10?

`gopeaks -b LK3-B_K4me3_filt_tn5correct.bam -o gopeaks_output/LK3-B_K4me3_filt_tn5correct_gopeaks -s ????`

Is it equvivalent to MACS2 genomesize?

Best regards

**Comment by gartician** [comment]
Hi @Affebah,

Thank you for using GoPeaks! I agree that the documentation for the -s argument could be better, this will be fixed very soon. To use the chromosome size argument, please provide a file that contains a tab-separated file with two-columns of   chromosome name and size without column names. More specifically,

```
chr1    248956422
chr2    242193529
chr3    198295559
...
```

where the `...` is not part of the actual file, but a continuation of the pattern.

**Comment by gartician** [comment]
@Affebah

By default, GoPeaks will automatically import the chromosome sizes from the BAM file header. If this information is missing, it suggests an upstream tool could be overwriting some admittedly critical information which can raise a yellow flag for downstream analyses.

**Comment by Affebah** [comment]
Thank you for response @gartician

**Comment by Affebah** [comment]
Fixed
